services:
  - type: web
    name: device-tracker-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URI
        value: mongodb+srv://nethmi:Nelneth@2001@cluster0.zgrqgjb.mongodb.net/devicetracker?appName=Cluster0
      - key: PORT
        value: 10000