services:
  - type: web
    name: device-tracker-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URI
        value: mongodb+srv://nethmi:Nethmi123@cluster0.zgrqgjb.mongodb.net/devicetracker?retryWrites=true&w=majority
      - key: PORT
        value: 10000